name: Deploy

on: [push]
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out master and get private submodules
        uses: actions/checkout@master
        with:
          submodules: recursive
          fetch-depth: 1
          token: ${{ secrets.PTOKEN }}
      - name: Sync Submodule
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Commit Update
        run: |
          git config --global user.name 'Git Bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
      - name: Install latest Hugo
        run: |
          HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name')
          mkdir tmp/ && cd tmp/
          curl -sSL https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/hugo_extended_${HUGO_VERSION: -7}_Linux-64bit.tar.gz | tar -xvzf-
          sudo mv hugo /usr/local/bin/
          cd .. && rm -rf tmp/
          hugo version
      - name: Build site
        run: hugo --minify --cleanDestinationDir
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
          
  deploy:
    environment:
      name: github-pages
      url: https://testingifthishugostuffworks.github.io
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
